name: Tests Python

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Configurer Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
    - name: Installer les dépendances
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-mock colorama requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Exécuter les tests
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        pytest tests/